### ISSUE TITLE
Can phaseLD use for outcross F1 population?

### ISSUE THREAD

**Issue by xiekunwhy** [plantformatics/phaseLD#1]
Hi @plantformatics ,

Can phaseLD use for outcross (cross between two heterogeneous parents) F1 populations ?

Best wishes,
Kun

**Comment by plantformatics** [comment]
I originally wrote this software to phase SNVs from a pseudo-testcross population (het x hom parents). If you know which markers are heterozygous in parent A and homozygous in parent B (and vice versa), you can run phaseLD twice for each set of parent-specific segregating markers. That is, you need to have polymorphism information for your parents as well as the progeny. phaseLD will only work with biallelic variants coded as "a" and "A", which is why you will need two sets of SNP input to run independently for each parent. 

This is exactly what we ended up do after we discovered residual heterozygosity in our inbred parent (detailed in this publication: https://www.genetics.org/content/212/1/317).

**Comment by xiekunwhy** [comment]
Thank you for your reply.

I will try to run phaseLD twice for each set of parent-specific segregation markers. But I have an other question that if I can keep hkxhk markers when doing parent-specific phasing in order to merge sex-specific genetic map?

Best,
Kun

**Comment by plantformatics** [comment]
phaseLD is designed to work with polymorphisms on a physical map (e.g. SNPs/INDELs on a reference genome assembly). It outputs phased variants denoted as 0 or 1 for the focus parental haplotypes as well as recombination bins (physical windows separated by a single recombination event, also in 0/1 format) for each individual in your F1 population. You can simply take the union of bin maps/variants for each individual, from each map, to get parent of origin haplotypes. Inclusion of heterozygous markers in both parents will confuse the software. 

**Advice for running phaseLD:**

- I recommend running phaseLD with the `--quick` flag. It is way faster and as, if not more, accurate than the defaults. 
- Input markers should be sorted `sort -k1,1V input > input.sorted`
- The choice of the `r2` parameter will depend on LD in your population/species. Increasing r2 will increase the stringency of marker consideration. You will likely need to adjust for each chromosome. 
- if your goal to create a genetic map in genetic distances (cM), you can convert the output of phaseLD (haplotype bin map) for input into genetic mapping software. I like the speed and accuracy of MSTMap (https://doi.org/10.1371%2Fjournal.pgen.1000212)

**Comment by xiekunwhy** [comment]
Thank you  very much, and I will try following your suggestions.

Best,
Kun
